CREATE TABLE CLIENTS(
    id BIGSERIAL PRIMARY KEY,
    client_name VARCHAR(200) NOT NULL,
    email VARCHAR(200) NOT NULL,
    address VARCHAR(500) NOT NULL,
    date_of_birth DATE NOT NULL);

CREATE TYPE product_type AS ENUM('RETIREMENT', 'TFSA', 'SAVINGS');

CREATE TABLE FINANCIAL_PRODUCTS(
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    type product_type NOT NULL);

CREATE TABLE CLIENT_PRODUCTS(
    id BIGSERIAL PRIMARY KEY,
    client_id BIGINT NOT NULL,
    financial_product_id BIGINT NOT NULL,
    balance DECIMAL(20,2);

ALTER TABLE CLIENT_PRODUCTS ADD CONSTRAINT fk_client_id FOREIGN KEY (client_id) REFERENCES CLIENTS(id);
ALTER TABLE CLIENT_PRODUCTS ADD CONSTRAINT fk_financial_products_id FOREIGN KEY (financial_product_id) REFERENCES FINANCIAL_PRODUCTS(id);